name: Create Release with latest archive
on:
  push:
    tags:
       - '*'
jobs:
  build:ss
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: 'modules/'
        filename: 'ahojplatby-latest-release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "modules/ahojplatby-latest-release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
